{% set provider = "prometheus" %}
{% set goname = "github.com/prometheus/"+provider.lower() %}
{% set version = "2.19.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: b72b9b6bdbae246dcc29ef354d429425eb3c0a6e1596fc8b29b502578a4ce045

build:
  skip: true  # [win]
  number: 0
  script:
    - pushd {{ pkg_src }}/cmd/{{ name }}
    - GOBIN=$(go env GOBIN)  # [not win]
    - go build -v -o $GOBIN/{{ name }} .       # [unix]
    - go build -v -o %GOBIN%\{{ name }}.exe .  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  requires:
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - prometheus --version

about:
  home: https://prometheus.io/
  license: Apache-2.0
  license_file: {{ pkg_src }}/LICENSE
  summary: Prometheus, a Cloud Native Computing Foundation project, is a systems and service monitoring system.
  doc_url: https://prometheus.io/docs/introduction/overview/
  dev_url: https://github.com/prometheus/{{ name }}

extra:
  recipe-maintainers:
    - rluria14
    - adbeda
    - mwilson8
    - oblute
